

INSERT INTO orders (user_pk, shipment_pk, title, guest_mobile, total_price, total_quantity, total_count, status, created_at) 
VALUES 
(7, 1, '한우 소고기 외 3건', NULL, 50000, 5, 3, 'paid', NOW()),
(7, 2, '프라임 스테이크 셋트', NULL, 30000, 3, 2, 'shipping', NOW()),
(7, 3, '랍스터 스페셜 세트', NULL, 80000, 2, 1, 'delivered', NOW()),
(7, 1, '한우 소고기 외 3건', NULL, 50000, 5, 3, 'paid', NOW()),
(7, 2, '프라임 스테이크 셋트', NULL, 30000, 3, 2, 'shipping', NOW()),
(7, 3, '랍스터 스페셜 세트', NULL, 80000, 2, 1, 'delivered', NOW()),
(7, 1, '한우 소고기 외 3건', NULL, 50000, 5, 3, 'paid', NOW()),
(7, 2, '프라임 스테이크 셋트', NULL, 30000, 3, 2, 'shipping', NOW()),
(7, 3, '랍스터 스페셜 세트', NULL, 80000, 2, 1, 'delivered', NOW()),
(7, 1, '한우 소고기 외 3건', NULL, 50000, 5, 3, 'paid', NOW()),
(7, 2, '프라임 스테이크 셋트', NULL, 30000, 3, 2, 'shipping', NOW()),
(7, 3, '랍스터 스페셜 세트', NULL, 80000, 2, 1, 'delivered', NOW()),
(7, 1, '한우 소고기 외 3건', NULL, 50000, 5, 3, 'paid', NOW()),
(7, 2, '프라임 스테이크 셋트', NULL, 30000, 3, 2, 'shipping', NOW()),
(7, 3, '랍스터 스페셜 세트', NULL, 80000, 2, 1, 'delivered', NOW()),
(7, 1, '한우 소고기 외 3건', NULL, 50000, 5, 3, 'paid', NOW()),
(7, 2, '프라임 스테이크 셋트', NULL, 30000, 3, 2, 'shipping', NOW()),
(7, 3, '랍스터 스페셜 세트', NULL, 80000, 2, 1, 'delivered', NOW())
;
